public class main
{

  public static void main(string[] arg){
    system.out.printl("");
    system.out.printl("Clase de programacion II");
    system.out.printl("");
    system.out.printl("\n\n\t\tEjercicio N°1");
    system.out.printl("");
    system.out.printl("");

    int var1 =20;
    int var2 =50;

    system.out.printl("La suma de la variable var1 + var2="+(var1+var2));
    system.out.printl("La resta de la variable var1 - var2="-(var1-var2));
    system.out.printl("La multiplicacion de la variable var1 * var2="*(var1*var2));
    system.out.printl("La division de la variable var1 / var2="/(var1/var2));
  {



}